# Generated by Django 5.0.2 on 2024-02-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_holder_type',
            field=models.CharField(choices=[('G', 'General'), ('S', 'Supervisor')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
