# Generated by Django 5.0.2 on 2024-02-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_upitransaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinetransaction',
            name='transaction_type',
            field=models.CharField(choices=[('D', 'Debit'), ('C', 'Credit')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
