# Generated by Django 5.0.2 on 2024-02-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_onlinetransaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='loandetail',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
