# Generated by Django 5.0.2 on 2024-02-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_loandetail_tenure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandetail',
            name='loan_account_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
