# Generated by Django 5.0.2 on 2024-02-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_loandetail_always_yes_because_of_signals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandetail',
            name='always_yes_because_of_signals',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loandetail',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loandetail',
            name='loan_active',
            field=models.BooleanField(default=False),
        ),
    ]
