# Generated by Django 5.0.2 on 2024-02-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_alter_loandetail_always_yes_because_of_signals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixeddeposit',
            name='interest',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='maturity_amount',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=90),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='fixed_deposit_number',
            field=models.CharField(max_length=255),
        ),
    ]
