# Generated by Django 5.0.2 on 2024-02-09 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0011_fixeddeposit_tenure'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreditCard',
        ),
    ]
